# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

#cache:
#  - c:\RLibrary
  
environment:
  USE_RTOOLS: true
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  PKGTYPE: binary


# Adapt as necessary starting from here

build_script:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - travis-tool.sh install_deps
  - travis-tool.sh install_github iNZightVIT/iNZightTools@dev
  - travis-tool.sh install_github iNZightVIT/iNZightPlots@dev
  - appveyor DownloadFile "http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.22/gtk+-bundle_2.22.1-20101227_win32.zip" -FileName gtk32.zip
  - appveyor DownloadFile "http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip" -FileName gtk64.zip
  - md gtk
  - cd gtk
  - md i386
  - cd i386
  - 7z x ..\..\gtk32.zip > nul
  - cd ..
  - md x64
  - cd x64
  - 7z x ..\..\gtk64.zip > nul
  - cd ..
  - cd ..
  - if exist c:\RLibrary\RGtk2\gtk\ rd /s /q c:\RLibrary\RGtk2\gtk
  - mv gtk c:\RLibrary\RGtk2
  - del gtk32.zip
  - del gtk64.zip

test_script:
  - md C:\Users\appveyor\Documents\iNZightVIT
  - travis-tool.sh run_tests

on_success:
  - Rscript -e "covr::codecov()"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
