context("Code writing")

# load_all("../iNZightPlots")

# try(ui$close()); load_all()
ui <- iNZGUI$new()
ui$initializeGui()
on.exit(gWidgets2::dispose(ui$win))
Sys.sleep(2)

test_that("Data set code is applied", {
    cas <- census.at.school.500
    attr(cas, "code") <- "read_csv('cas.csv')"
    ui$setDocument(iNZDocument$new(data = cas), reset = TRUE)
    Sys.sleep(2)

    expect_match(
        gsub("\\s\\s+", " ", paste(ui$rhistory$get(), collapse = " ")),
        "data <- read_csv('cas.csv')",
        fixed = TRUE
    )
})

test_that("magrittr library call is included", {
    expect_match(
        gsub("\\s\\s+", " ", paste(ui$rhistory$get(), collapse = " ")),
        "library(magrittr)",
        fixed = TRUE
    )
})

test_that("Plot code is generated correctly", {
    svalue(ui$ctrlWidget$V1box) <- "height"
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height, data = data)"
    )

    svalue(ui$ctrlWidget$V2box) <- "travel"
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ travel, data = data)"
    )

    svalue(ui$ctrlWidget$G1box) <- "gender"
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ travel | gender, data = data)"
    )

    svalue(ui$ctrlWidget$G2box) <- "age"
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ travel | gender, data = data)"
    )

    sld <- ui$ctrlWidget$ctrlGp$children[[1]]$children[[15]]
    sld$set_index(2L)
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ travel | gender + age, g2.level = \"[7 - 11]\", data = data)"
    )


    svalue(ui$ctrlWidget$V2box, TRUE) <- 1L
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ . | gender + age, g2.level = \"[7 - 11]\", data = data)"
    )

    svalue(ui$ctrlWidget$G1box, TRUE) <- 1L
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ . | age, data = data, g1.level = \"[7 - 11]\")"
    )

    sld$set_index(1L)
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height, data = data)"
    )

    svalue(ui$ctrlWidget$G2box, TRUE) <- 1L
    svalue(ui$ctrlWidget$G1box) <- "gender"
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ . | gender, data = data)"
    )
    svalue(ui$ctrlWidget$G1box, TRUE) <- 1L
})

test_that("Plot code generated by add to plot - colour by", {
    svalue(ui$ctrlWidget$V1box) <- "travel"
    expect_true(ui$plotToolbar$addToPlot(message = FALSE))

    # fill colour by gender
    tbl <- ui$moduleWindow$body$children[[1]]$children[[1]]
    wi <- which(
        sapply(seq_len(tbl$get_dim()[["nrow"]]),
            function(i) {
                z <- svalue(tbl[i,1]) == "Colour by :"
                length(z) && z
            }
        )
    )
    ci <- which(
        sapply(tbl$child_positions, function(x) identical(x$child, tbl[wi, 3]))
    )
    colby <- tbl$children[[ci]]
    suppressWarnings(colby$set_value("gender"))
    expect_equal(as.character(ui$getActiveDoc()$getSettings()$colby), "gender")
    expect_equal(ui$getActiveDoc()$getSettings()$col.fun, "contrast")

    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(travel, colby = gender, data = data, col.fun = \"contrast\")"
    )

    colby$set_index(1L)
    ui$moduleWindow$footer$children[[2]]$invoke_change_handler()

    svalue(ui$ctrlWidget$V1box) <- "height"
    svalue(ui$ctrlWidget$V2box) <- "armspan"
    expect_true(ui$plotToolbar$addToPlot(message = FALSE))

    tbl <- ui$moduleWindow$body$children[[1]]$children[[1]]
    wi <- which(
        sapply(seq_len(tbl$get_dim()[["nrow"]]),
            function(i) {
                z <- svalue(tbl[i,1]) == "Colour by :"
                length(z) && z
            }
        )
    )
    ci <- which(
        sapply(tbl$child_positions, function(x) identical(x$child, tbl[wi, 3]))
    )
    colby <- tbl$children[[ci]]

    suppressWarnings(colby$set_value("gender"))
    expect_equal(as.character(ui$getActiveDoc()$getSettings()$colby), "gender")
    expect_equal(ui$getActiveDoc()$getSettings()$col.fun, "contrast")

    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ armspan, colby = gender, data = data, col.fun = \"contrast\")"
    )

    suppressWarnings(colby$set_value("age"))
    expect_equal(as.character(ui$getActiveDoc()$getSettings()$colby), "age")
    expect_equal(ui$getActiveDoc()$getSettings()$col.fun, "viridis")

    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ armspan, colby = age, data = data, col.fun = \"viridis\")"
    )

    ## Emphasize

    colby$set_index(1)
    ui$moduleWindow$footer$children[[2]]$invoke_change_handler()
})

# try(ui$close()); load_all()
# if (interactive()) {
#     ui <- iNZGUI$new()
#     ui$initializeGui(census.at.school.500)
#     on.exit(gWidgets2::dispose(ui$win))
#     Sys.sleep(2)
# }

test_that("Plot code generated by add to plot - size by", {
    svalue(ui$ctrlWidget$V1box) <- "height"
    svalue(ui$ctrlWidget$V2box) <- "armspan"
    expect_true(ui$plotToolbar$addToPlot(message = FALSE))

    # fill colour by gender
    tbl <- ui$moduleWindow$body$children[[1]]$children[[1]]
    wi <- which(
        sapply(seq_len(tbl$get_dim()[["nrow"]]),
            function(i) {
                z <- svalue(tbl[i,1]) == "Resize points by :"
                length(z) && z
            }
        )
    )
    ci <- which(
        sapply(tbl$child_positions, function(x) identical(x$child, tbl[wi, 3]))
    )
    sizeby <- tbl$children[[ci]]
    suppressWarnings(sizeby$set_value("age"))
    expect_equal(as.character(ui$getActiveDoc()$getSettings()$sizeby), "age")

    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ armspan, sizeby = age, data = data)"
    )

    # emphasize
    pri <- which(
        sapply(tbl$child_positions, function(x) identical(x$child, tbl[wi + 1, 3]))
    )
    prop <- tbl$children[[pri]]
    expect_equal(svalue(prop), "proportional")
    svalue(prop) <- "emphasize"
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ armspan, sizeby = age, data = data, resize.method = \"emphasize\")"
    )

    expect_silent(svalue(sizeby, index = TRUE) <- 1)
    sizeby$set_index(1)
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ armspan, data = data)"
    )

    ui$moduleWindow$footer$children[[2]]$invoke_change_handler()
})

if (FALSE) {
    # try(ui$close()); load_all()
    ui <- iNZGUI$new()
    ui$initializeGui(census.at.school.500)
    on.exit(gWidgets2::dispose(ui$win))
    Sys.sleep(2)
}

# w <- gwindow()
# g <- ggroup(container=w)
# m <- gmenu(
#     list(gcheckbox("Linear", parent=w), gcheckbox("Quadratic", parent=w)),
#     popup=TRUE
# )
# b <- gbutton("Click me", handler = m, container = g)
# addPopupMenu(b, m)


test_that("Plot code generated by add to plot - symbol by", {
    svalue(ui$ctrlWidget$V1box) <- "height"
    svalue(ui$ctrlWidget$V2box) <- "armspan"
    expect_true(ui$plotToolbar$addToPlot(message = FALSE))

    # fill colour by gender
    tbl <- ui$moduleWindow$body$children[[1]]$children[[1]]
    wi <- which(
        sapply(seq_len(tbl$get_dim()[["nrow"]]),
            function(i) {
                z <- svalue(tbl[i,1]) == "Symbol by :"
                length(z) && z
            }
        )
    )
    ci <- which(
        sapply(tbl$child_positions, function(x) identical(x$child, tbl[wi, 3]))
    )
    symby <- tbl$children[[ci]]
    suppressWarnings(symby$set_value("gender"))
    expect_equal(as.character(ui$getActiveDoc()$getSettings()$symbolby), "gender")

    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ armspan, symbolby = gender, data = data)"
    )

    symby$set_index(1)
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(height ~ armspan, data = data)"
    )

    ui$moduleWindow$footer$children[[2]]$invoke_change_handler()
})


test_that("Plot code generated by add to plot - cat x cat", {
    svalue(ui$ctrlWidget$V1box) <- "travel"
    suppressWarnings(svalue(ui$ctrlWidget$V2box) <- "gender")
    expect_true(ui$plotToolbar$addToPlot(message = FALSE))

    # fill colour by gender
    tbl <- ui$moduleWindow$body$children[[1]]$children[[1]]
    wi <- which(
        sapply(seq_len(tbl$get_dim()[["nrow"]]),
            function(i) {
                z <- svalue(tbl[i,1]) == "Colour palette : "
                length(z) && z
            }
        )
    )
    ci <- which(
        sapply(tbl$child_positions, function(x) identical(x$child, tbl[wi, 3]))
    )
    colpal <- tbl$children[[ci]]
    suppressWarnings(colpal$set_index(2L))
    expect_equal(as.character(ui$getActiveDoc()$getSettings()$col.fun), "bright")

    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(travel ~ gender, data = data, col.fun = \"bright\")"
    )

    suppressWarnings(colpal$set_index(1L))
    expect_equal(
        attr(ui$curPlot, "code"),
        "inzplot(travel ~ gender, data = data, col.fun = \"contrast\")"
    )

    ui$moduleWindow$footer$children[[2]]$invoke_change_handler()
})

ui$close()

data(api, package = "survey")
# try(ui$close(), TRUE); load_all()
ui <- iNZGUI$new()
ui$initializeGui(apiclus1)
on.exit(gWidgets2::dispose(ui$win))
Sys.sleep(2)

ui$getActiveDoc()$getModel()$setDesign(
    clus1 = "dnum", wt = "pw", fpc = "fpc", type = "survey", gui = ui
)

test_that("Survey design code is valid", {
    svalue(ui$ctrlWidget$V1box) <- "enroll"
    expect_equal(ui$plotType, "hist")
    expect_equal(attr(ui$curPlot, "code"), "inzplot(enroll, design = data.svy)")

    smry <- iNZGetSummary$new(ui)
    on.exit(gWidgets2::dispose(smry$win))
    expect_match(svalue(smry$code_box), "inzsummary(enroll, design = data.svy)", fixed = TRUE)
    gWidgets2::dispose(smry$win)

    inf <- iNZGetInference$new(ui)
    on.exit(gWidgets2::dispose(inf$win))
    expect_match(
        svalue(inf$code_box),
        "inzinference(enroll, design = data.svy, hypothesis = NULL)",
        fixed = TRUE
    )

    expect_silent(inf$hypothesis_test$set_index(2L))
    expect_silent(inf$hyp_null$set_value(500))
    expect_match(
        svalue(inf$code_box),
        "inzinference(enroll, design = data.svy, hypothesis.value = 500)",
        fixed = TRUE
    )
})
