iNZcodeWidget <- setRefClass(
    "iNZcodeWidget",
    fields = list(
        GUI = "ANY",
        history = "list",      ## each list is a vector of commands
        keep.last = "logical", ## if FALSE, the last element of history is replaced on update
        packages = "character"
    ),
    methods = list(
        initialize = function(gui) {
            initFields(GUI = gui, keep.last = TRUE,
                       packages = c("iNZightPlots", "magrittr"))
            history <<- list()
        },
        add = function(x, keep = FALSE, tidy = TRUE) {
            if (tidy && requireNamespace("formatR", quietly = TRUE)) 
                x <- capture.output(formatR::tidy_source(text = x, width.cutoff = 60))
            if (!keep.last) history <<- history[-length(history)]
            history <<- c(history, list(c("", x)))
            keep.last <<- keep
            ## append any new packages ...?
            if (any(grepl("::", x))) {
                sapply(x[grepl("::", x)], function(y) {
                    m <- regexpr("\ [a-zA-Z0-9]+::", y)
                    pkg <- substr(y, m + 1, m + attr(m, "match.length") - 3)
                    if (!pkg %in% packages) packages <<- c(packages, pkg)
                })
            }
            invisible(NULL)
        },
        get = function() {
            return(c(header(), do.call(c, history)))
        },
        update = function() {
            ## look at the data - has it got code? update the history with the code!
            code <- GUI$getActiveDoc()$getCode()
            if (!is.null(code)) {
                dname <- sprintf("data%s", ifelse(GUI$activeDoc == 1, "", GUI$activeDoc))
                code <- gsub(".dataset", dname, code, fixed = TRUE)
                ## append data<- to first non-comment line
                cmmt <- grepl("^#", code)
                code[which(!cmmt)[1]] <- paste0(dname, " <- ", code[which(!cmmt)[1]])
                add(code, keep = TRUE)
            } else {
                add("## NOTE:  missing code")
            }
        },
        header = function() {
            c("# iNZight Code History",
              "",
              sprintf("## This script was automatically generated by iNZight v%s", packageVersion("iNZight")),
              "",
              "## BETA WARNING: we're still working on making this as accurate",
              "##               as possible, so please ... ",
              "##  - expect 'gaps' in the generated code (i.e., missing actions), and",
              "##  - LET US KNOW if you think something's missing",
              "##    (if you can give a minimal step-by-step to reproduce the problem, ",
              "##     that would be incredibly useful!)",
              "##    email: inzight_support@stat.auckland.ac.nz",
              "",
              "## -------------------------------------------------------------------------- ##",
              "",
              "## This script assumes you have various iNZight packages installed.",
              "## Uncomment the following lines if you don't:",
              "",
              sprintf("# install.packages(c('%s'), ", paste(packages, collapse = "',\n#                    '")),
              "#     repos = c('http://r.docker.stat.auckland.ac.nz/R',",
              "#               'https://cran.rstudio.com'))",
              "",
              "## -------------------------------------------------------------------------- ##",
              "")
        }
    )
)
